[profile.default]
src = "src"
out = "out"
libs = ["lib"]
test = "test"
cache_path = "cache"
broadcast = "broadcast"

# Solidity compiler settings
solc_version = "0.8.24"
optimizer = true
optimizer_runs = 200
via_ir = true
evm_version = "shanghai"

# Testing settings
verbosity = 2
fuzz_runs = 1000
fuzz_max_test_rejects = 65536

# Gas settings
gas_limit = 9223372036854775807
gas_price = 20000000000

# RPC settings
eth_rpc_url = "${ETH_RPC_URL}"
blockdag_testnet_rpc_url = "${BLOCKDAG_TESTNET_RPC_URL}"
blockdag_mainnet_rpc_url = "${BLOCKDAG_MAINNET_RPC_URL}"

# Etherscan settings
etherscan_api_key = "${ETHERSCAN_API_KEY}"

# Formatting settings
line_length = 100
tab_width = 4
bracket_spacing = true
int_types = "long"

# Additional settings
auto_detect_solc = false
offline = false
force = false
no_storage_caching = false
no_rpc_rate_limiting = false

# Remappings
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "@forge-std/=lib/forge-std/src/",
    "ds-test/=lib/forge-std/lib/ds-test/src/",
]

# Profile for CI/CD
[profile.ci]
fuzz_runs = 10000
verbosity = 4

# Profile for production deployment
[profile.production]
optimizer = true
optimizer_runs = 1000000
via_ir = true

# Profile for local development
[profile.local]
optimizer = false
verbosity = 3

# RPC endpoints configuration
[rpc_endpoints]
mainnet = "${ETH_RPC_URL}"
sepolia = "${SEPOLIA_RPC_URL}"
goerli = "${GOERLI_RPC_URL}"
blockdag_testnet = "${BLOCKDAG_TESTNET_RPC_URL}"
blockdag_mainnet = "${BLOCKDAG_MAINNET_RPC_URL}"
localhost = "http://127.0.0.1:8545"

# Etherscan configuration
[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}" }
sepolia = { key = "${ETHERSCAN_API_KEY}" }
goerli = { key = "${ETHERSCAN_API_KEY}" }
blockdag_testnet = { key = "${BLOCKDAG_EXPLORER_API_KEY}", url = "https://testnet-explorer.blockdag.network/api" }
blockdag_mainnet = { key = "${BLOCKDAG_EXPLORER_API_KEY}", url = "https://explorer.blockdag.network/api" }
